name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          project: ./src/zhaoliru
      - name: Generate report
        run: npm run cypress:report:zhaoliru
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        if: failure()
        with: 
          name: cypress-screenshots
          path: |
            src/zhaoliru/cypress/results/
            src/zhaoliru/cypress/screenshots/
